
-- Adel Khorramrouz
-- ak8480@rit.edu
-- 04/13/2023
-- PE09

-- MAKE SURE TO DROP THE DATABASE IF IT EXISTS
DROP DATABASE IF EXISTS PE09;

-- CREATE THE DATABASE
CREATE Database PE09;

-- Use this Database
USE PE09;

-- STRONG ENTITY OF THE RELATIONSHIP TWEEET
CREATE TABLE TWEET (
    TWEET_ID INT NOT NULL AUTO_INCREMENT,
    TWEET_TEXT VARCHAR(140) NOT NULL,
    TWEET_DATE DATETIME NOT NULL,
    TWEET_USER_ID INT NOT NULL,
    PRIMARY KEY (TWEET_ID)
);


-- weak entity of the relationship MENTION
CREATE TABLE MENTION (
    MENTION_ID INT NOT NULL AUTO_INCREMENT,
    TWEET_ID INT NOT NULL,
    MENTION_USER_ID INT NOT NULL,
    MENTION_TEXT VARCHAR(140) NOT NULL,
    PRIMARY KEY (MENTION_ID),
    FOREIGN KEY (TWEET_ID) REFERENCES TWEET(TWEET_ID)
);


-- populate the tweet table
INSERT INTO TWEET (TWEET_TEXT, TWEET_DATE, TWEET_USER_ID) VALUES ('I am Ali', '2017-10-10 10:10:10', 1);
INSERT INTO TWEET (TWEET_TEXT, TWEET_DATE, TWEET_USER_ID) VALUES ('I am Sara', '2017-10-11 10:10:10', 2);
INSERT INTO TWEET (TWEET_TEXT, TWEET_DATE, TWEET_USER_ID) VALUES ('I am John', '2017-10-12 10:10:10', 3);
INSERT INTO TWEET (TWEET_TEXT, TWEET_DATE, TWEET_USER_ID) VALUES ('I ma Adel', '2017-10-13 10:10:10', 4);
INSERT INTO TWEET (TWEET_TEXT, TWEET_DATE, TWEET_USER_ID) VALUES ('I ma Adel Again After one year', '2018-10-10 10:10:10', 4);
INSERT INTO TWEET (TWEET_TEXT, TWEET_DATE, TWEET_USER_ID) VALUES ('I am John, It has been a year since my last tweet', '2018-11-10 10:10:10', 3);
INSERT INTO TWEET (TWEET_TEXT, TWEET_DATE, TWEET_USER_ID) VALUES ('Hi Adel, Missed you long time no see', '2018-11-11 10:10:10', 2);


-- populate the mention table
INSERT INTO MENTION (TWEET_ID, MENTION_USER_ID, MENTION_TEXT) VALUES (1, 2, 'Hi Ali, How are you?');
INSERT INTO MENTION (TWEET_ID, MENTION_USER_ID, MENTION_TEXT) VALUES (2, 3, 'Hi Sara, How are you?');
INSERT INTO MENTION (TWEET_ID, MENTION_USER_ID, MENTION_TEXT) VALUES (3, 4, 'Hi John, How are you?');
INSERT INTO MENTION (TWEET_ID, MENTION_USER_ID, MENTION_TEXT) VALUES (4, 1, 'Hi Adel, How are you?');
INSERT INTO MENTION (TWEET_ID, MENTION_USER_ID, MENTION_TEXT) VALUES (2, 2, 'I am glad all is good Sara?');
INSERT INTO MENTION (TWEET_ID, MENTION_USER_ID, MENTION_TEXT) VALUES (3, 3, 'I am glad, all is good John?');


