CREATE DATABASE PE03P1;
USE PE03P1;

CREATE TABLE A(
`3` INT UNSIGNED NOT NULL,
`2` INT UNSIGNED NOT NULL,
`9` INT UNSIGNED NOT NULL,
`8` INT UNSIGNED NOT NULL,
`6` INT UNSIGNED NOT NULL,
`5` INT UNSIGNED NOT NULL,
`4` INT UNSIGNED NOT NULL,
PRIMARY KEY(`3`,`2`));